// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDiMlbgLG4Kp_386T9pONt5VY1xkIXyPI',
    appId: '1:193407198246:web:f049c1d32e30bd1cfe72e7',
    messagingSenderId: '193407198246',
    projectId: 'hydropod-12ef6',
    authDomain: 'hydropod-12ef6.firebaseapp.com',
    databaseURL: 'https://hydropod-12ef6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydropod-12ef6.appspot.com',
    measurementId: 'G-CZNHPZBX1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzt5yHgMvpLuChsBml0qUk0hL32GtJQis',
    appId: '1:193407198246:android:24af27f0cea9ad1cfe72e7',
    messagingSenderId: '193407198246',
    projectId: 'hydropod-12ef6',
    databaseURL: 'https://hydropod-12ef6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydropod-12ef6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPA_oBkQCSLcDNxZzMg34QBtOkUWg5FXA',
    appId: '1:193407198246:ios:1868d052e0bf98cffe72e7',
    messagingSenderId: '193407198246',
    projectId: 'hydropod-12ef6',
    databaseURL: 'https://hydropod-12ef6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydropod-12ef6.appspot.com',
    iosClientId: '193407198246-to51bnr0vkitvtmvm3vlgm8u9ue5g980.apps.googleusercontent.com',
    iosBundleId: 'com.autobonics.hydropodHydroponics',
  );
}
